version: '3.8'

networks:
  default:
    name: kdt

volumes:
  data:
    driver: local
  config:
    driver: local

services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
      - config:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=ENC(KUQPNozqm8BhAT3tT30P9hB7VllUovWo)
      - MYSQL_USER=ENC(GGO0fgzs3AA/MidOHKNG6w==)
      - MYSQL_PASSWORD=ENC(KUQPNozqm8BhAT3tT30P9hB7VllUovWo)
    platform: linux/arm64/v8
    restart: always
